# Generated by Django 4.2.3 on 2023-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member1",
            name="gender",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
