# Generated by Django 4.2.4 on 2023-08-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member1_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member1",
            name="gender",
        ),
    ]
